// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCufmJp8PFXLP9vl7Xn_pJbe6KkAdniexs',
    appId: '1:136590577861:web:1fc63b2fed215ed04fe0ac',
    messagingSenderId: '136590577861',
    projectId: 'attendance-system-cb3e1',
    authDomain: 'attendance-system-cb3e1.firebaseapp.com',
    storageBucket: 'attendance-system-cb3e1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa1N6NBj6Qp1-tNaCLkmLfUBUJkWNDXVw',
    appId: '1:136590577861:android:ca1fea34f4940b8e4fe0ac',
    messagingSenderId: '136590577861',
    projectId: 'attendance-system-cb3e1',
    storageBucket: 'attendance-system-cb3e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW2ViNybb2322Gr8pyg97lmewgrd-LA9Q',
    appId: '1:136590577861:ios:0d5555444cc05f6b4fe0ac',
    messagingSenderId: '136590577861',
    projectId: 'attendance-system-cb3e1',
    storageBucket: 'attendance-system-cb3e1.firebasestorage.app',
    iosBundleId: 'com.example.digitalAttendanceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW2ViNybb2322Gr8pyg97lmewgrd-LA9Q',
    appId: '1:136590577861:ios:0d5555444cc05f6b4fe0ac',
    messagingSenderId: '136590577861',
    projectId: 'attendance-system-cb3e1',
    storageBucket: 'attendance-system-cb3e1.firebasestorage.app',
    iosBundleId: 'com.example.digitalAttendanceSystem',
  );
}
